### PR TITLE
Final admin dashboard changes

### PR DESCRIPTION
**Pull request by EarthenSky**
For https://github.com/CSSS/csss-site-backend/issues/2
Related to https://github.com/CSSS/csss-site-frontend/pull/62 and https://github.com/CSSS/csss-site-frontend/pull/51

changes
- small bugfixes
- take in list for /new_term endpoint

### CODE REVIEW

**Comment by EarthenSky** [comment]
Changes
- ...
- refactor methods so that uploaded data does not include data computed by the backend
- ...

**Comment by micahdbak** [comment]
Done or naw?

**Comment by EarthenSky** [comment]
> Done or naw?

Nope, but getting close!! I've done enough research into how the google drive api works to know that we only need to attempt to assign the user to their permission to check if their email is valid. I'm thinking I'll leave stronger permission checks for later though  (https://github.com/CSSS/csss-site-backend/issues/82).

**Comment by EarthenSky** [comment]
Oh dear, I was hoping something like this wouldn't happen again; breaking things into smaller PRs is going to be a goal in the future!

Changes
- a list of new officer terms can be created in a single transaction (for the admin page)
- daily cron support was merged here from https://github.com/CSSS/csss-site-backend/pull/72 (but that feature is still not done yet)
- many small bug fixes

- reformat github module
- add extra github functions for getting permissions
- add google drive module & add functions for getting & setting drive permissions (TODO in #72)
- reformat discord module
- add extra functions to discord module for listing 
- add integration tests for the discord, github, and google modules, plus documentation for running them under the wiki. I've also tested several of these on prod to ensure they work!

- add email module that has not been tested
- add auth/info endpoint for getting current user's info
- add GET officers/info/{computing_id} endpoint for getting private officer info
- remove is_filled_in column from officer tables
- add PATCH officers/info/{computing_id} endpoint for updating officer info
- add PATCH officers/term/{term_id} endpoint for updating officer term id

- lots of refactoring so that code is mostly dry

**Comment by EarthenSky** [comment]
"move fast and break things"

**Pull request merged**
